
spring.profiles.active: development

spring.datasource.username: sa
spring.datasource.password:
spring.datasource.driverClassName: org.h2.Driver
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

# Max file size.
spring.http.multipart.max-file-size: 1Mb
# Max request size.
spring.http.multipart.max-request-size: 10Mb


logging.level:
  org.springframework.web: INFO
  org.apache.tomcat: INFO

#security.user.name: bioplat
#security.user.password: Bi0plat
#management.security.roles: SUPERUSER
management.security.enabled: false

---

spring:
  profiles: production
  datasource.url: jdbc:h2:${classifiers.datasource.dbfile:./db/classifiers-db};DB_CLOSE_ON_EXIT=FALSE
  jpa.hibernate.ddl-auto: validate

---

spring:
  profiles: development
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
liquibase.enabled: true
