
spring.profiles.active: production

spring.datasource.url: jdbc:h2:./db/classifiers-db;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username: sa
spring.datasource.password:
spring.datasource.driverClassName: org.h2.Driver
spring.jpa.hibernate.ddl-auto: validate

# Max file size.
spring.http.multipart.max-file-size: 1Mb
# Max request size.
spring.http.multipart.max-request-size: 10Mb