

spring.datasource.url: jdbc:h2:./db/classifiers-db;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username: sa
spring.datasource.password:
spring.datasource.driverClassName: org.h2.Driver
spring.jpa.hibernate.ddl-auto: validate
